services:
  postgres:
    image: bitnami/postgresql
    environment:
      POSTGRES_USER: fastfeet
      POSTGRES_PASSWORD: fastfeet
      POSTGRES_DB: fastfeet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: